### ISSUE TITLE
502 Bad Gateway when I try to delete projects

### ISSUE THREAD

**Issue by mlbtc** [transitcenter/tesca#3] opened 2023-10-04 21:45 UTC
From the project page, I get a 502 Bad Gateway when I try to delete projects. Many of those projects themselves were created and then abandoned because I got an error message (Interal Server Error) after TESCA tried to load the opportunities csv.

<img width="1430" alt="image" src="https://github.com/transitcenter/tesca/assets/84036764/9be90f38-152d-410e-87ce-f1b2cf35ceff">
<img width="899" alt="image" src="https://github.com/transitcenter/tesca/assets/84036764/717bc2ac-6278-4ba6-878a-74c335957558">

**Comment by wklumpen** [comment] 2023-10-10 16:13
Found the cause: If an error occurs to cause some sort of issue before the initial `config.yml` is created, the delete-projects approach does not work:

```
File ".../app.py", line 131, in get_config
    with open(os.path.join(CACHE_FOLDER, str(analysis_id), "config.yml"), "r") as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/20231005195824/config.yml'
```

Will add a fix for this.

**Comment by wklumpen** [comment] 2023-10-10 16:45
Fix made to save the configuration file before we try to do any processing. This ensures that a configuration file *should* exist no matter what happens, meaning the project can then be deleted/accessed.

Also updated Gunicorn webserver logs to make it easier to diagnose problems in the future.

**Closed by wklumpen** 2023-10-10 16:45 UTC
Labels: bug
